openapi: 3.0.0
info:
  title: Modus Times Public API
  version: 1.0.0
  description: >
    This is a mock API for demo purposes inside Confluence using the Just Add+ Swagger macro.
    It includes editorial-style content for testing layouts and presentation.

servers:
  - url: https://api.modustimes.com/v1

paths:
  /articles:
    get:
      summary: Get list of articles
      operationId: listArticles
      responses:
        '200':
          description: A list of articles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Article'

  /articles/{id}:
    get:
      summary: Get article by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Full article
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Article'
        '404':
          description: Not found

components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        author:
          type: string
        publishDate:
          type: string
          format: date
        body:
          type: string
